[package]
name = "polkadot-collator-protocol"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bitvec = { version = "1.0.1", default-features = false, features = ["alloc"] }
futures = "0.3.21"
futures-timer = "3"
gum = { package = "tracing-gum", path = "../../gum" }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "vstakhov-yamux-window" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "vstakhov-yamux-window" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "vstakhov-yamux-window" }

polkadot-primitives = { path = "../../../primitives" }
polkadot-node-network-protocol = { path = "../../network/protocol" }
polkadot-node-primitives = { path = "../../primitives" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-node-subsystem = {path = "../../subsystem" }
fatality = "0.0.6"
thiserror = "1.0.31"
tokio-util = "0.7.1"

[dev-dependencies]
log = "0.4.17"
env_logger = "0.9.0"
assert_matches = "1.4.0"

sp-core = { git = "https://github.com/paritytech/substrate", features = ["std"] , branch = "vstakhov-yamux-window" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "vstakhov-yamux-window" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "vstakhov-yamux-window" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "vstakhov-yamux-window" }
parity-scale-codec = { version = "3.6.1", features = ["std"] }

polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
